networks:
  internal:
    ipam:
      driver: default
      config:
        - subnet: "10.53.0.0/24"

services:
  resolver:
    image: ghcr.io/dnstapir/unbound:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 443:443/tcp
      - 443:443/udp
      - 853:853/tcp
    volumes:
      - ./unbound/local.d/access-control.conf:/etc/unbound/local.d/access-control.conf:ro
      - ./unbound/conf.d/dnstap.conf:/etc/unbound/conf.d/dnstap.conf:ro
    networks:
      internal:
        ipv4_address: 10.53.0.10
    deploy:
      resources:
        limits:
          memory: 4G
  edm-init:
    image: busybox
    volumes:
      - edm-data:/var/lib/edm
    command: chown -v 65532:65532 /var/lib/edm
  edm:
    image: ghcr.io/dnstapir/edm:latest
    volumes:
      - ./keys:/etc/dnstapir/keys:ro
      - ./edm/config:/etc/dnstapir/edm:ro
      - edm-data:/var/lib/edm
    networks:
      internal:
        ipv4_address: 10.53.0.11
    deploy:
      resources:
        limits:
          memory: 4G
    command:
     - run
     - --input-tcp=10.53.0.11:53535
     - --minimiser-workers=3
     - --disable-session-files
     - --disable-histogram-sender
     - --config=/etc/dnstapir/edm/edm.toml
     - --well-known-domains=/etc/dnstapir/edm/well-known-domains.dawg
     - --mqtt-signing-key-file=/etc/dnstapir/keys/jws.key
     - --mqtt-signing-key-id=${NAME}
     - --mqtt-ca-file=/etc/dnstapir/keys/ca.crt
     - --mqtt-client-cert-file=/etc/dnstapir/keys/tls.crt
     - --mqtt-client-key-file=/etc/dnstapir/keys/tls.key
     - --mqtt-server=tls://mqtt.dev.dnstapir.se:8883
     - --mqtt-topic=events/up/${NAME}/edm
     - --mqtt-client-id=${NAME}-edm-pub
     - --http-url=https://aggregates.dev.dnstapir.se
     - --http-signing-key-file=/etc/dnstapir/keys/jws.key
     - --http-client-cert-file=/etc/dnstapir/keys/tls.crt
     - --http-client-key-file=/etc/dnstapir/keys/tls.key
     - --http-signing-key-id=${NAME}
    depends_on:
     edm-init:
       condition: service_completed_successfully
  pop:
    image: leons-tapir-pop
    volumes:
      - ./pop/etc/pop-globalconfig.yaml:/etc/dnstapir/pop-globalconfig.yaml
      - ./pop/etc/pop-outputs.yaml:/etc/dnstapir/pop-outputs.yaml
      - ./pop/etc/pop-policy.yaml:/etc/dnstapir/pop-policy.yaml
      - ./pop/etc/pop-sources.yaml:/etc/dnstapir/pop-sources.yaml
      - ./pop/etc/rpz-serial.txt:/etc/dnstapir/rpz-serial.txt
      - ./pop/etc/tapir-pop.yaml:/etc/dnstapir/tapir-pop.yaml
      - ./pop/var/tmp/local-feed.txt:/var/tmp/dnstapir/local-feed.txt
      - ./pop/var/tmp/local-whitelist.txt:/var/tmp/dnstapir/local-whitelist.txt
      - ./pop/var/log:/var/log/dnstapir
      - ./keys/ca.crt:/etc/dnstapir/certs/ca.crt
      - ./keys/jws.key:/etc/dnstapir/certs/jws.key
      - ./keys/mqtt.tem.general.validatorkey.pem:/etc/dnstapir/certs/jws-public.key
      - ./keys/tls.crt:/etc/dnstapir/certs/tls.crt
      - ./keys/tls.key:/etc/dnstapir/certs/tls.key
      - ./keys/tls.crt:/etc/dnstapir/certs/tapir-pop.crt # Ugly hack because POP has this name hardcoded in the source
      - ./keys/tls.key:/etc/dnstapir/certs/tapir-pop.key # Ugly hack because POP has this name hardcoded in the source
      - ./tapir-cli/etc/tapir-cli.yaml:/etc/dnstapir/tapir-cli.yaml
    networks:
      internal:
        ipv4_address: 10.53.0.100
    deploy:
      resources:
        limits:
          memory: 4G
    command:
      - /usr/local/libexec/tapir-pop
      - -v
volumes:
  edm-data:
